### ISSUE TITLE
Errors while trying to build in Eclipse RT druid

### ISSUE THREAD

**Issue by abhinav2003** [evidence/erika3#1]
Hello

I am doing my grad research on one of the open source RTOS and i came across the Erika Enterprise. 
So when I saw this code on github, I tried to test it using the RT druid from eclipse and it shows me errors regarding the HIGH and LOW in example 1 of the 5 examples provided.
![1](https://user-images.githubusercontent.com/16267760/46589965-2d03ac80-ca75-11e8-9386-13774e2e19d6.PNG)
Is there any way that you can help me around with this?
I am new to dealing with real time operating systems so any help would be much appreciated.

**Comment by pj1974** [comment]
Please ignore those errors. They are printed by CDT, because CDT has not been instructed about all libraries and compiler available.

Please also send all questions to the ERIKA3 Forum!!!

Ciao, PJ
