### ISSUE TITLE
Build TC397 error use RT-Druid

### ISSUE THREAD

**Issue by Jeepgoing** [evidence/erika3#9]
I am testing build TC397 follow [RT-Druid](https://www.erika-enterprise.com/wiki/index.php/Infineon_Tricore_AURIX_build_with_RT-Druid#RT-Druid_Template_Project), but when i build project, an error occur.

> 16:37:50 **** Incremental Build of configuration Default for project ERIKA ****
> make all 
> make[1]: Entering directory '/cygdrive/d/dongsheng/AUTOSAR/TC397/workspace/erika/ERIKA/out'
> APP_TARGETS=erika3app.dump
> make[2]: Entering directory '/cygdrive/d/dongsheng/AUTOSAR/TC397/workspace/erika/ERIKA/erika'
> ERIKA_FILES=/cygdrive/d/dongsheng/AUTOSAR/TC397/eclipse-rtdruid3-photon-win32-x86_64_20190524_gh65/eclipse/plugins/com.eu.evidence.ee3_3.0.1.20190524_gh65/ee_files
> make[3]: Entering directory '/cygdrive/d/dongsheng/AUTOSAR/TC397/workspace/erika/ERIKA/erika'
> AR   libee.a
> D:\dongsheng\AUTOSAR\TC397\toolchain\tricore_gcc494_mingw_bins-main\tricore_494_mingw\bin\tricore-ar.exe: illegal option -- -
> Usage: D:\dongsheng\AUTOSAR\TC397\toolchain\tricore_gcc494_mingw_bins-main\tricore_494_mingw\bin\tricore-ar.exe [--error-numbers] [emulation options] [-]{dmpqrstx}[abcfilNoPsSuvV] [member-name] [count] archive-file file...
>        D:\dongsheng\AUTOSAR\TC397\toolchain\tricore_gcc494_mingw_bins-main\tricore_494_mingw\bin\tricore-ar.exe [--error-numbers] -M [<mri-script]
>  commands:
>   d               - delete file(s) from the archive

**Comment by gserano** [comment]
Dear @Jeepgoing ,
  please downgrade your GNU Make to version 4.3.
  
  BR,
    G.

**Comment by Jeepgoing** [comment]
> downgrade

Thanks.

**Comment by Jeepgoing** [comment]
> Dear @Jeepgoing , please downgrade your GNU Make to version 4.3.
> 
> BR, G.

Thanks
